//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistories
    {
        public System.Guid LoginHistory_Id { get; set; }
        public string LoanOfficerEmployeeNumber { get; set; }
        public string LoanOfficerFirstName { get; set; }
        public string LoanOfficerLastName { get; set; }
        public System.DateTime LoginDatetime { get; set; }
        public string UserName { get; set; }
    }
}
