//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOS_LoanOfficer_Lookup
    {
        public System.Guid LOS_LoanOfficer_Id { get; set; }
        public string Avatar { get; set; }
        public string Email { get; set; }
        public string EmployeeNumber { get; set; }
        public string Fax { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string NMLS { get; set; }
        public string URL_Web { get; set; }
    }
}
