//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtors_Master
    {
        public System.Guid user_id { get; set; }
        public string avatar { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public Nullable<bool> preferred { get; set; }
        public string last_name { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string user_name { get; set; }
        public string unique_user_key { get; set; }
    }
}
