//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtors_Extension
    {
        public System.Guid Realtor_Extension_Id { get; set; }
        public System.Guid User_Id { get; set; }
        public string Avatar { get; set; }
        public string CompanyName { get; set; }
        public bool IsPreferredIndicator { get; set; }
    }
}
