//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypes
    {
        public System.Guid UserType_Id { get; set; }
        public string Type { get; set; }
    }
}
