//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhml.Mms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid User_Id { get; set; }
        public System.Guid UserType_Id { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string ForgotPassword { get; set; }
        public bool ForgotPasswordIndicator { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string UniqueUserKey { get; set; }
        public System.DateTime UpdatedDatetime { get; set; }
        public string UserName { get; set; }
    }
}
