//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Rhml.Mms;

namespace Rhml.Mms.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MmsModels : DbContext
    {
        public MmsModels()
            : base("name=MmsModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LoginHistories> LoginHistories { get; set; }
        public DbSet<LOS_LoanOfficer_Lookup> LOS_LoanOfficer_Lookup { get; set; }
        public DbSet<Realtors_Extension> Realtors_Extension { get; set; }
        public DbSet<Realtors_Master> Realtors_Master { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserTypes> UserTypes { get; set; }
    }
}
